### ISSUE TITLE
apply_field function

### ISSUE THREAD

**Issue by mfizyczka** [pyplati/platipy#114]
Hi,
in the example:
https://colab.research.google.com/github/pyplati/platipy/blob/master/examples/generate_synthetic_head_neck_deformation.ipynb#scrollTo=oPWUCvwIMpbj

you're using apply_field but it is not defined. Could you please specify how to import this function?

Thanks in advance

**Comment by rnfinnegan** [comment]
Hello!
Thanks for pointing this out. 
This notebook uses an older version of `platipy`, but I will update it soon.

The correct function to use is `apply_transform`, which can be found in `platipy.imaging.registration.utils.apply_transform`.

Let me know if you need any further assistance!

Rob

**Comment by pchlap** [comment]
This has been corrected in the example `generate_synthetic_head_neck_deformation.ipynb` Jupyter notebook.
