### ISSUE TITLE
Package platipy with new pynetdicom import  

### ISSUE THREAD

**Issue by dalmouiee** [pyplati/platipy#158]
Hi @pchlap, is it possible to package the newest version platipy and publish to PIP please when possible? The new pynetdicom import isn't in the latest package and is problematic for building new pydicer lock files with the newest version of pynetdicom, thanks!

**Comment by pchlap** [comment]
Yep hopefully this will be ready to go in the next week or two. I just have to sort out those open PRs before making a new release :)
