### ISSUE TITLE
Examples in docs

### ISSUE THREAD

**Issue by pchlap** [pyplati/platipy#162]
- [x] Visualisation (already exists)
- [ ] Image registration (Rob)
- [x] Atlas based segmentation (Phil)
- [ ] Synthetic deformation (fast example) (Rob)
- [x] Contour comparison metrics (Phil)
- [x] DVH analysis (already exists)
- [x] Bronchus segmentation page (maybe) (Phil)
- [ ] Update README with images from examples and link to examples (both)

**Comment by rnfinnegan** [comment]
Could use dummy data (cylinder, spheres) for some of these
