### ISSUE TITLE
numpy >1.18 has no np.alen()

### ISSUE THREAD

**Issue by nis** [pyplati/platipy#164]
It's used here: https://github.com/pyplati/platipy/blob/4814826b0a3cd8e6a4eebc549c0122bcbbdc37a8/platipy/dicom/io/crawl.py#L592

len(...) can be used instead of np.alen(...), but I'm unsure how backwards compatible it is.

np.alen(...) was depreceated in 1.18: https://numpy.org/devdocs/release/1.18.0-notes.html#deprecate-np-alen

**Comment by pchlap** [comment]
Thanks for the bug report @nis.

@rnfinnegan, it seems that there shouldn't be any problem simply replacing `np.alen()` with `len()` here?

**Comment by rnfinnegan** [comment]
Yes, should be fine!

**Comment by pchlap** [comment]
This should be resolved in v0.6.0
