### ISSUE TITLE
Conversion of dicom structure to nii.gz doesn't retain holes in structure

### ISSUE THREAD

**Issue by nickhardcastle** [pyplati/platipy#244]
Hi team,

When using convert_rtstruct, if there's a hole in the structure in the dicom, this isn't retained. The resultant nii.gz fills in the hole in the structure.

I noticed this while converting ring structures.

Cheers,

Nick

**Comment by pchlap** [comment]
Thanks for reporting this @nickhardcastle! We will look into it.

**Comment by kirbyju** [comment]
Hi, any update on this?  We've got some new datasets in TCIA where this is an issue.  

Btw, it's super cool that you built in support to pull data from us directly!  I'm planning to advertise this in of our social media posts sometime soon :-)

**Comment by pchlap** [comment]
Hi @kirbyju, thanks for reaching out. To be honest both @rnfinnegan and I have been caught up with other things. But hopefully this is something that would be fairly straightforward to resolve.

@rnfinnegan when we catch up in a couple of weeks can we discuss how to do this? It would be good to have a sample RTSTRUCT to use for development? Perhaps you could generate something on a phantom? Once we have that I think it should be fairly easy to adapt our function to support this.

@kirbyju we'll keep you posted on how it goes :)

**Comment by pchlap** [comment]
Hi @kirbyju, @nickhardcastle,

Sorry for the delay in fixing this issue. @rnfinnegan and I had a chance to meet yesterday to debug this. Turns out the solution was pretty simple! (See #271).

Rob created a test dataset using Eclipse for us to test this. But it might be good to get some more test data to confirm this fixes the issue entirely. Do either of you have data you might be able to share? Alternatively would it be feasible to test out the fix before we build a release? I will aim to generate some test data using MIM and RF AutoContour this weekend.

Rob and I will address a few other minor issues and will prepare a new release of platipy including this fix in about 3-4 weeks.

**Comment by kirbyju** [comment]
I think this one would be useful to try. You can download it here: https://nbia.cancerimagingarchive.net/nbia-search/?saved-cart=nbia-31061718290468281

<img width="1569" alt="Screenshot 2024-06-13 at 10 05 44 AM" src="https://github.com/pyplati/platipy/assets/2379527/b2cdc49e-6f6b-4ce1-a620-03c04c97f71d">

**Comment by pchlap** [comment]
> I think this one would be useful to try. You can download it here: https://nbia.cancerimagingarchive.net/nbia-search/?saved-cart=nbia-31061718290468281

Thanks @kirbyju, this TCIA example seems to convert fine. However there isn't a hole in this particular structure, just 2d islands which platipy is converting to a mask fine. Or have I missed something?

I also tested this today with an RTSTRUCT generated in MIM and RF AutoContour where I created a strucutre with a hole inside. These holes are now appearing in the masks generated.

**Comment by kirbyju** [comment]
My mistake, wasn't thinking straight. Glad it seems to be working in all circumstances though!

**Comment by cutright** [comment]
> Hi sorry to rehash the issue, but I do think holes are ignored... and I think I have a simple fix. Maybe someone could confirm?
> 
> It's my understanding that if a contour overlaps with the previous contour in the sequence, it is considered a hole... if it does not overlap then it is an island. So essentially each contour in the sequence should toggle the mask's value at a point, rather than always increment it by 1.
> 
> I think a simple fix is to use `image_blank % 2 == 1` instead of `image_blank > 0` here:
> 
> [platipy/platipy/dicom/io/rtstruct_to_nifti.py](https://github.com/pyplati/platipy/blob/b1168be1162837f996a0ca99166fdb4c6f664bc9/platipy/dicom/io/rtstruct_to_nifti.py#L212)
> 
> Line 212 in [b1168be](/pyplati/platipy/commit/b1168be1162837f996a0ca99166fdb4c6f664bc9)
> 
>  struct_image = sitk.GetImageFromArray(1 * (image_blank > 0))

I think I see now. `image_blank` is binary and toggles using  the ^= operator. I think this was mentioned in another GH issue. So `image_blank > 0` is the same result as `image_blank % 2 == 1` https://github.com/pyplati/platipy/blob/b1168be1162837f996a0ca99166fdb4c6f664bc9/platipy/dicom/io/rtstruct_to_nifti.py#L209
