### ISSUE TITLE
urllib error on clusters in run_hybrid_segmentation

### ISSUE THREAD

**Issue by Ken32g** [pyplati/platipy#260]
When running `run_hybrid_segmentation `on HPC clusters, it may report the following error: `urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>`. This error is likely raised because the cluster nodes cannot access the data URL. Therefore, `run_hybrid_segmentation` needs to be executed on a login node for the first time. After the dataset has been downloaded, the task can be submitted onto the HPC cluster, and it should work properly.

**Comment by pchlap** [comment]
Hi @Ken32g, thanks for flagging this. The tool will download the models etc on first run so I this wouldn't work if there is no internet connection on the cluster. It sounds like you have a solution but in case it is useful, check the .platipy directory in your users home directory as this is where it downloads the models. You can copy that directory to other locations to bypass having to redownload the model everytime.

**Comment by Ken32g** [comment]
Thank you!
