### ISSUE TITLE
TCIA functionality is using a deprecated API

### ISSUE THREAD

**Issue by kirbyju** [pyplati/platipy#276]
It looks like you're accessing https://services.cancerimagingarchive.net/services/v4/TCIA to access data from TCIA.  We deprecated this version of the API in 2022 so you're pulling stale information in terms of the list of collections/data that are available.  It might be easiest if you retire this functionality from platipy and update example notebooks where you want to pull TCIA data to use https://pypi.org/project/tcia-utils/.  Alternatively you can review https://wiki.cancerimagingarchive.net/display/Public/TCIA+Programmatic+Interface+REST+API+Guides for information about how to update your code to get the currently available data.

**Comment by pchlap** [comment]
Thanks for reporting this @kirbyju. I agree, best to retire the this functionality. I'll self assign this and will hopefully be able to address this soon.
