### ISSUE TITLE
can't install platipy[cardiac]

### ISSUE THREAD

**Issue by jaketakes** [pyplati/platipy#288]
Hi, I'm having an issue installing platipy[cardiac] because of a dependency issue I think. I've been able to install `platipy` just fine but with `platipy[cardiac]` it fails installing `nnunet`.

The first error it hits is:
  Building wheels for collected packages: nnunet
  Building wheel for nnunet (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [441 lines of output]
      C:\Users\80029824\.conda\envs\plat2\lib\site-packages\setuptools\dist.py:450: SetuptoolsDeprecationWarning: Invalid dash-separated options

And at the end the error is:

` error: could not create 'build\bdist.win-amd64\wheel\.\nnunet\experiment_planning\alternative_experiment_planning\pooling_and_convs\experiment_planner_baseline_3DUNet_poolBasedOnSpacing.py': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nnunet
  Running setup.py clean for nnunet
Failed to build nnunet
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (nnunet)`

I've tried the solutions people have posted to similar error messages, but nothing has worked so far. I'm using python 3.9.19 and I've already upgraded setuptools, build, wheel, and pip.

**Comment by pchlap** [comment]
Hi @jaketakes, based on those logs it looks like you are trying to install this on Windows? nnUNet v1 (which platipy uses here) doesn't support Windows. So even if you managed to get this dependency to build I don't imagine that you'd have much luck running the tool.

Are you able to install and run this on a Linux based OS? You could consider using Windows Subsystem for Linux (WSL).

We have discussed upgrading this part to nnUNet v2 which would support Windows (see https://github.com/pyplati/platipy/issues/141#issuecomment-1902648321). But neither @rnfinnegan or I have the capacity to do this at the moment.

**Comment by jaketakes** [comment]
@pchlap Ah I didn't realize that. I'll run it on Linux then, thank you.
